version: '3'

services:
  db:
    image: mongo
    ports: 
      - "27017:27017"
  web:
    build: .
    command: python ./file_storage/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db