version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7
      - image: circleci/mongo:latest
        environment:
          # environment:
          MONGODB_USERNAME: "admin"
          MONGODB_PASSWORD: "admin"
          
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            cd file_storage
            python manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app
        